
project_id = "oxeccsmxqymvxycnaszo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
api_port = 54326
web_port = 54327

[storage]
enabled = true
port = 54328
image_transformation_enabled = true

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54330

[[edge_functions.function]]
name = "create-payment"
verify_jwt = true

[[edge_functions.function]]
name = "create-stripe-session"
verify_jwt = true

[[edge_functions.function]]
name = "create-payment-intent"
verify_jwt = true

[[edge_functions.function]]
name = "process-payment-success"
verify_jwt = false

[[edge_functions.function]]
name = "sync-pending-payments"
verify_jwt = false
