project_id = "oxeccsmxqymvxycnaszo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54329
max_depth = 12
max_nodes = 60
batch_size = 10
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
jwt_secret_warning = "WARNING: jwt_secret should be a strong random string, at least 32 characters long."

[db]
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation_enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://casooculto.com.br", "https://caso-oculto.vercel.app"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.admin-list-users]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.create-stripe-session]
verify_jwt = false

[functions.fix-user-packs]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.process-payment-success]
verify_jwt = false

[functions.send-refund-notification]
verify_jwt = false

[functions.stripe-payment-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sync-pending-payments]
verify_jwt = false

[functions.sync-stripe-payments]
verify_jwt = false