// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxeccsmxqymvxycnaszo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94ZWNjc214cXltdnh5Y25hc3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NjEwMTYsImV4cCI6MjA2NzMzNzAxNn0.wYbeCVKuCR3W_Ep4MtAp-1UbaIuQCcc43KsvAGFemAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});